# Generated by Django 4.0.4 on 2022-04-28 18:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_article_createdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 28, 21, 50, 42, 727356)),
        ),
    ]
