# Generated by Django 4.0.4 on 2022-04-28 19:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0007_executors_alter_article_createdat_article_executor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='executor',
            new_name='execut',
        ),
        migrations.AlterField(
            model_name='article',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 28, 22, 34, 10, 181974)),
        ),
    ]
