# Generated by Django 4.0.4 on 2022-04-28 19:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0008_rename_executor_article_execut_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='execut',
            new_name='executor',
        ),
        migrations.AlterField(
            model_name='article',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 28, 22, 35, 4, 803667)),
        ),
    ]
